"""One-shot generator for the šifranik djelatnosti constants.

Reads docs/Šifranik djelatnosti.xlsx (the HZZO list of activity codes) and
regenerates two checked-in artifacts:

- backend/app/sifranik_djelatnosti.py
- frontend/src/lib/sifranik-djelatnosti.ts

Run after a šifranik update:

    PYTHONIOENCODING=utf-8 python backend/scripts/extract_sifranik_djelatnosti.py

The .xlsx is NOT read at runtime - the generated modules are the source.
"""

from __future__ import annotations

import re
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[2]
XLSX = ROOT / "docs" / "Šifranik djelatnosti.xlsx"
BACKEND_OUT = ROOT / "backend" / "app" / "sifranik_djelatnosti.py"
FRONTEND_OUT = ROOT / "frontend" / "src" / "lib" / "sifranik-djelatnosti.ts"

CODE_RE = re.compile(r"^[0-9]{7}$")


def load_rows() -> list[tuple[str, str]]:
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    ws = wb.active
    rows: list[tuple[str, str]] = []
    for code, name in ws.iter_rows(min_row=2, values_only=True):
        if code is None or name is None:
            continue
        code_s = str(code).strip()
        name_s = str(name).strip()
        if not CODE_RE.match(code_s):
            raise ValueError(f"unexpected šifra value: {code_s!r}")
        rows.append((code_s, name_s))
    return rows


def py_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def ts_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def write_backend(rows: list[tuple[str, str]]) -> None:
    lines = [
        '"""Generated by backend/scripts/extract_sifranik_djelatnosti.py - do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "SIFRANIK_DJELATNOSTI: tuple[tuple[str, str], ...] = (",
    ]
    for code, name in rows:
        lines.append(f'    ("{code}", "{py_escape(name)}"),')
    lines.append(")")
    lines.append("")
    lines.append("SIFRANIK_DJELATNOSTI_BY_CODE: dict[str, str] = dict(SIFRANIK_DJELATNOSTI)")
    lines.append("")
    BACKEND_OUT.write_text("\n".join(lines), encoding="utf-8")


def write_frontend(rows: list[tuple[str, str]]) -> None:
    lines = [
        "// Generated by backend/scripts/extract_sifranik_djelatnosti.py - do not edit by hand.",
        "",
        "export type SifranikDjelatnostiGroup = '1' | '2' | '3' | '4' | '5' | '6' | '7';",
        "",
        "export interface SifranikDjelatnostiEntry {",
        "  code: string;",
        "  name: string;",
        "  group: SifranikDjelatnostiGroup;",
        "}",
        "",
        "export const SIFRANIK_DJELATNOSTI: ReadonlyArray<SifranikDjelatnostiEntry> = [",
    ]
    for code, name in rows:
        group = code[0]
        lines.append(f"  {{ code: '{code}', name: '{ts_escape(name)}', group: '{group}' }},")
    lines.append("];")
    lines.append("")
    lines.append("export const SIFRANIK_DJELATNOSTI_BY_CODE: ReadonlyMap<string, SifranikDjelatnostiEntry> = new Map(")
    lines.append("  SIFRANIK_DJELATNOSTI.map((entry) => [entry.code, entry] as const),")
    lines.append(");")
    lines.append("")
    FRONTEND_OUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    rows = load_rows()
    print(f"loaded {len(rows)} rows from {XLSX}")
    write_backend(rows)
    write_frontend(rows)
    print(f"wrote {BACKEND_OUT}")
    print(f"wrote {FRONTEND_OUT}")


if __name__ == "__main__":
    main()
