"""add_patients_table

Revision ID: 25d5ef4e9bfd
Revises: ad76d96d3e35
Create Date: 2026-03-24 16:42:55.926759

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25d5ef4e9bfd"
down_revision: str | Sequence[str] | None = "ad76d96d3e35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ime", sa.String(length=100), nullable=False),
        sa.Column("prezime", sa.String(length=100), nullable=False),
        sa.Column("datum_rodjenja", sa.Date(), nullable=True),
        sa.Column("spol", sa.String(length=1), nullable=True),
        sa.Column("oib", sa.String(length=11), nullable=True),
        sa.Column("mbo", sa.String(length=9), nullable=True),
        sa.Column("adresa", sa.String(length=255), nullable=True),
        sa.Column("grad", sa.String(length=100), nullable=True),
        sa.Column("postanski_broj", sa.String(length=10), nullable=True),
        sa.Column("telefon", sa.String(length=50), nullable=True),
        sa.Column("mobitel", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("napomena", sa.Text(), nullable=True),
        sa.Column("alergije", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("spol IN ('M', 'Z')", name="ck_patient_spol"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "mbo", name="uq_patient_tenant_mbo"),
        sa.UniqueConstraint("tenant_id", "oib", name="uq_patient_tenant_oib"),
    )
    op.create_index("ix_patient_tenant_prezime", "patients", ["tenant_id", "prezime"], unique=False)
    op.create_index(op.f("ix_patients_tenant_id"), "patients", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_tenant_id"), table_name="patients")
    op.drop_index("ix_patient_tenant_prezime", table_name="patients")
    op.drop_table("patients")
    # ### end Alembic commands ###
