"""add_cezih_euputnice_table

Revision ID: b9d406b44dcc
Revises: f4f65b63ad7f
Create Date: 2026-03-25 00:23:34.790499

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9d406b44dcc"
down_revision: str | Sequence[str] | None = "f4f65b63ad7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cezih_euputnice",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column("datum_izdavanja", sa.String(length=20), nullable=False),
        sa.Column("izdavatelj", sa.String(length=200), nullable=False),
        sa.Column("svrha", sa.String(length=200), nullable=False),
        sa.Column("specijalist", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cezih_euputnice_external_id"), "cezih_euputnice", ["external_id"], unique=False)
    op.create_index(op.f("ix_cezih_euputnice_tenant_id"), "cezih_euputnice", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cezih_euputnice_tenant_id"), table_name="cezih_euputnice")
    op.drop_index(op.f("ix_cezih_euputnice_external_id"), table_name="cezih_euputnice")
    op.drop_table("cezih_euputnice")
    # ### end Alembic commands ###
