"""add_appointments_table

Revision ID: c1af963d4ec1
Revises: 25d5ef4e9bfd
Create Date: 2026-03-24 17:03:50.779235

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1af963d4ec1"
down_revision: str | Sequence[str] | None = "25d5ef4e9bfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("doktor_id", sa.UUID(), nullable=False),
        sa.Column("datum_vrijeme", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trajanje_minuta", sa.Integer(), server_default="30", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="zakazan", nullable=False),
        sa.Column("vrsta", sa.String(length=50), server_default="pregled", nullable=False),
        sa.Column("napomena", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('zakazan', 'potvrdjen', 'u_tijeku', 'zavrsen', 'otkazan', 'nije_dosao')",
            name="ck_appointment_status",
        ),
        sa.CheckConstraint(
            "vrsta IN ('pregled', 'kontrola', 'lijecenje', 'higijena', 'konzultacija', 'hitno')",
            name="ck_appointment_vrsta",
        ),
        sa.ForeignKeyConstraint(
            ["doktor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_appointments_doktor", "appointments", ["tenant_id", "doktor_id", "datum_vrijeme"], unique=False)
    op.create_index("ix_appointments_patient", "appointments", ["tenant_id", "patient_id"], unique=False)
    op.create_index("ix_appointments_tenant_date", "appointments", ["tenant_id", "datum_vrijeme"], unique=False)
    op.create_index(op.f("ix_appointments_tenant_id"), "appointments", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_appointments_tenant_id"), table_name="appointments")
    op.drop_index("ix_appointments_tenant_date", table_name="appointments")
    op.drop_index("ix_appointments_patient", table_name="appointments")
    op.drop_index("ix_appointments_doktor", table_name="appointments")
    op.drop_table("appointments")
    # ### end Alembic commands ###
