"""add_procedures_medical_records

Revision ID: cb18236e67df
Revises: a8c3e2f1d5b7
Create Date: 2026-03-24 17:53:05.095589

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb18236e67df"
down_revision: str | Sequence[str] | None = "a8c3e2f1d5b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "procedures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sifra", sa.String(length=20), nullable=False),
        sa.Column("naziv", sa.String(length=255), nullable=False),
        sa.Column("opis", sa.Text(), nullable=True),
        sa.Column("cijena_cents", sa.Integer(), server_default="0", nullable=False),
        sa.Column("trajanje_minuta", sa.Integer(), server_default="30", nullable=False),
        sa.Column("kategorija", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "sifra", name="uq_procedure_tenant_sifra"),
    )
    op.create_index(op.f("ix_procedures_tenant_id"), "procedures", ["tenant_id"], unique=False)
    op.create_table(
        "medical_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("doktor_id", sa.UUID(), nullable=False),
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("datum", sa.Date(), nullable=False),
        sa.Column("tip", sa.String(length=30), nullable=False),
        sa.Column("dijagnoza_mkb", sa.String(length=10), nullable=True),
        sa.Column("dijagnoza_tekst", sa.String(length=255), nullable=True),
        sa.Column("sadrzaj", sa.Text(), nullable=False),
        sa.Column("cezih_sent", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("cezih_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cezih_reference_id", sa.String(length=100), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doktor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_medical_records_patient", "medical_records", ["tenant_id", "patient_id", "datum"], unique=False)
    op.create_index(op.f("ix_medical_records_tenant_id"), "medical_records", ["tenant_id"], unique=False)
    op.create_table(
        "performed_procedures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("appointment_id", sa.UUID(), nullable=True),
        sa.Column("procedure_id", sa.UUID(), nullable=False),
        sa.Column("doktor_id", sa.UUID(), nullable=False),
        sa.Column("tooth_number", sa.Integer(), nullable=True),
        sa.Column("datum", sa.Date(), nullable=False),
        sa.Column("cijena_cents", sa.Integer(), nullable=False),
        sa.Column("napomena", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doktor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["procedure_id"],
            ["procedures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_performed_procedures_patient",
        "performed_procedures",
        ["tenant_id", "patient_id", "datum"],
        unique=False,
    )
    op.create_index(op.f("ix_performed_procedures_tenant_id"), "performed_procedures", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_performed_procedures_tenant_id"), table_name="performed_procedures")
    op.drop_index("ix_performed_procedures_patient", table_name="performed_procedures")
    op.drop_table("performed_procedures")
    op.drop_index(op.f("ix_medical_records_tenant_id"), table_name="medical_records")
    op.drop_index("ix_medical_records_patient", table_name="medical_records")
    op.drop_table("medical_records")
    op.drop_index(op.f("ix_procedures_tenant_id"), table_name="procedures")
    op.drop_table("procedures")
    # ### end Alembic commands ###
